### ISSUE TITLE
Replace default error page

### ISSUE THREAD

**Issue by ivarconr** [finn-no/tomcat7-docker#1]
Replace default error page (default is stacktrace) by adding the following into CATALINA_HOME/conf/web.xml.

```xml
 <error-page>
   <exception-type>java.lang.Throwable</exception-type>
   <location>/error.jsp</location>
 </error-page>
```
https://www.owasp.org/index.php/Securing_tomcat

**Comment by SimenB** [comment]
Should this be done for 7, 8, 9?
Also, shouldn't this be done by each application?

**Comment by ivarconr** [comment]
> Also, shouldn't this be done by each application?

Maybe, but then the documentation should tell you why and how.

**Comment by SimenB** [comment]
These images are hosted on company GH now, btw https://github.schibsted.io/finn/tomcat7-docker

@stigkj @chriswk Should these repos be properly deprecated/deleted?

**Comment by SimenB** [comment]
> Maybe, but then the documentation should tell you why and how.

This is a sensible default either way 😄
